apiVersion: v1
kind: Service
metadata:
  name: back
  namespace: iot
  labels:
    app: iot
    tier: back
spec:
  selector:
    app: iot
    tier: back
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: iot
  labels:
    app: iot
    tier: back
spec:
  selector:
    matchLabels:
      app: iot
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: iot
        tier: back
    spec:
      containers:
        - name: back
          image: mmontes11/iot-back:2.1.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - name: service-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/health-check
              port: service-port
          livenessProbe:
            httpGet:
              path: /api/health-check
              port: service-port
          envFrom:
            - configMapRef:
                name: back
            - secretRef:
                name: back
