apiVersion: v1
kind: Service
metadata:
  name: back
  namespace: iot
  labels:
    app: iot
    tier: back
spec:
  selector:
    app: iot
    tier: back
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: iot
  labels:
    app: iot
    tier: back
spec:
  selector:
    matchLabels:
      app: iot
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: iot
        tier: back
    spec:
      containers:
        - name: back
          image: mmontes11/iot-back:3.1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - name: service-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/health
              port: service-port
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/health
              port: service-port
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: back
            - secretRef:
                name: back
