apiVersion: v1
kind: ConfigMap
metadata:
  name: back
  namespace: iot
  labels:
    app: iot
    tier: back
data:
  DEBUG: "true"
  DEFAULT_CACHE_IN_SECONDS: "10"
  JWT_EXPIRATION: 1d
  MAX_DEFAULT_NEARBY_DISTANCE_IN_METERS: "10000"
  MAX_NUM_OF_THINGS_IN_STATS_RESULTS: "10"
  MONGO_URL: mongodb://mongo:27017/IoT
  MQTT_BROKER_HOST: mosquitto
  MQTT_BROKER_PORT: "1883"
  MQTT_BROKER_URL: mqtt://mosquitto:1883
  REDIS_URL: redis://redis:6379
  STATS_CACHE_IN_SECONDS: "10"
  THING_SOCKET_PORT: "8080"
  THING_SOCKET_URL: http://thing
