apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: iot
  labels:
    app: iot
    tier: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: iot
  labels:
    app: iot
    tier: cache
spec:
  selector:
    app: iot
    tier: cache
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: iot
  labels:
    app: iot
    tier: cache
spec:
  selector:
    matchLabels:
      app: iot
      tier: cache
  template:
    metadata:
      labels:
        app: iot
        tier: cache
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
              cpu: 125m
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: redis
