language: node_js
node_js:
  - "12.16"
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - jq
services:
  - docker
stages:
  - lint
  - test
  - build-check
  - build
  - publish-npm
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      before_script: ./scripts/ci-docker.sh
      script: npm test
      after_script: npm run coverage
    - stage: build-check
      script: npm run build
    - stage: build
      if: tag IS present
      before_install:
        - curl -fsSL https://get.docker.com | sh
        - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
        - mkdir -p $HOME/.docker
        - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
        - sudo service docker start
      install:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      script: ./scripts/build.sh
      skip_cleanup: true
      on:
        tags: true
    - stage: publish-npm
      if: tag IS present
      provider: script
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      script: npm run publish:npm
      skip_cleanup: true
      on:
        tags: true
