apiVersion: v1
kind: Service
metadata:
  name: biot
  namespace: iot
  labels:
    app: iot
    tier: bot
spec:
  selector:
    app: iot
    tier: bot
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biot
  namespace: iot
  labels:
    app: iot
    tier: bot
spec:
  selector:
    matchLabels:
      app: iot
      tier: bot
  template:
    metadata:
      labels:
        app: iot
        tier: bot
    spec:
      containers:
        - name: biot
          image: mmontes11/iot-biot:3.2.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 75m
            limits:
              memory: 64Mi
              cpu: 125m
          ports:
            - name: service-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/health
              port: service-port
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/health
              port: service-port
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: biot
            - secretRef:
                name: biot
