apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: iot
  labels:
    app: iot
    tier: reverse-proxy
spec:
  selector:
    app: iot
    tier: reverse-proxy
  ports:
    - port: 80
      name: http
    - port: 8080
      name: status
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: iot
  labels:
    app: iot
    tier: reverse-proxy
spec:
  selector:
    matchLabels:
      app: iot
      tier: reverse-proxy
  template:
    metadata:
      labels:
        app: iot
        tier: reverse-proxy
    spec:
      containers:
        - name: nginx
          image: mmontes11/iot-nginx:3.2.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "75m"
            limits:
              memory: "64Mi"
              cpu: "125m"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 8080
              name: status
