apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: iot
  labels:
    app: iot
    tier: front
spec:
  selector:
    app: iot
    tier: front
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: iot
  labels:
    app: iot
    tier: front
spec:
  selector:
    matchLabels:
      app: iot
      tier: front
  replicas: 1
  template:
    metadata:
      labels:
        app: iot
        tier: front
    spec:
      containers:
        - name: front
          image: mmontes11/iot-front:3.1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 75m
            limits:
              memory: 64Mi
              cpu: 125m
          ports:
            - containerPort: 80
